---
name: Build DMG

on:
  push:
    tags: "*"

jobs:
  build-dmg:
    runs-on: macos-15
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Prepare environment
        run: |
          brew install rust xz mise
          mise install
          eval "$(mise activate bash)"
          mix local.hex --force && mix local.rebar --force

      - name: build project
        run: |
          bash build.sh
          dmg_file=$(find src-tauri/target/release/bundle/dmg/ -type f -name "*.dmg")
          mv $dmg_file melocoton.dmg
          echo "dmg_file=melocoton.dmg" >> $GITHUB_ENV

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: melocoton
          path: ${{ env.dmg_file }}

      - name: Publish artifacts as release assets
        uses: softprops/action-gh-release@v2
        with:
          repository: erickgnavar/melocoton-releases
          body: ""
          tag_name: ${{ env.GITHUB_REF_NAME }}
          files: ${{ env.dmg_file }}
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          draft: false
          make_latest: true
